services:
  crok_server:
    container_name: crok_server
      #image: ee5610110106/crok:release_04102024
      #image: ee5610110106/crok:release_17102024_linux
    image: ee5610110106/crok:linux_18102024
      #build:
      #context: ./crok
    environment:
      - DEBUG=localtunnel*
      - SECURE=true
      - PORT=9003
      - USER_NAME=admin
      - PASS_WORD=QWer!@34
      - DATABASE_HOST=giantiot.com
      - DATABASE_PORT=45432
      - DATABASE_NAME=crok_db
      - DATABASE_USER=admin
      - DATABASE_PASS=qwer!@34
      - ACCESS_TOKEN_SECRET=
      - REFRESH_TOKEN_SECRET=
      - JWT_SECRET=y761WwEtZ0iDL1E9LwN6qhZdAlsiecWSv1p3y+OY4ws
      - JWT_REFRESH_SECRET=mfe30riCyGKwfH+sTmN7DDuJZ8nSkjJc/nuZfjfDxqs
    restart: always
    network_mode: "host"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
      #ports:
      #- "9003:${PORT}"
  crok-psotgresql:
      container_name: crok-psotgresql
      image: timescale/timescaledb:latest-pg14
      restart: always
      networks:
        - crok-network
      ports:
        - '45432:5432'
      environment:
        - TZ:"Asia/Bangkok"
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=qwer!@34
        - POSTGRES_DB=crok_db
      volumes:
        - ./data/timescaledb:/var/lib/postgresql/data
networks:
    crok-network: