services:
  crok_server:
    container_name: crok_server
    # image: ee5610110106/crok:release_25092024
    image: ee5610110106/crok:mac_test_env
    # image: ee5610110106/crok:v1_docker_compose
    environment:
      - DEBUG=localtunnel*
      - SECURE=true
      - PORT=9003
      - DATABASE_HOST=giantiot.com
      - DATABASE_PORT=45432
      - DATABASE_NAME=crok_dev
      - DATABASE_USER=admin
      - DATABASE_PASS=qwer!@34
      - ACCESS_TOKEN_SECRET=
      - REFRESH_TOKEN_SECRET=
      - JWT_SECRET=y761WwEtZ0iDL1E9LwN6qhZdAlsiecWSv1p3y+OY4ws
      - JWT_REFRESH_SECRET=mfe30riCyGKwfH+sTmN7DDuJZ8nSkjJc/nuZfjfDxqs
    restart: always
    network_mode: "default"
    ports:
      - "9003:9003"
